// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Qh3NdEYk5nl8j1o2HB_X0rpt0MFMW3E',
    appId: '1:1081850466656:web:cc4803059c970471eace05',
    messagingSenderId: '1081850466656',
    projectId: 'chat-app-540b1',
    authDomain: 'chat-app-540b1.firebaseapp.com',
    storageBucket: 'chat-app-540b1.appspot.com',
    measurementId: 'G-RFW9NTVZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-rcUsNnga7d956U-BCxSTzmVvgO-5Mc',
    appId: '1:1081850466656:android:cc89ec2d6224612ceace05',
    messagingSenderId: '1081850466656',
    projectId: 'chat-app-540b1',
    storageBucket: 'chat-app-540b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVk2CQZ4C5zOeyUBP_3zoJh1tTRB9D5Ek',
    appId: '1:1081850466656:ios:191f37a6a8201f94eace05',
    messagingSenderId: '1081850466656',
    projectId: 'chat-app-540b1',
    storageBucket: 'chat-app-540b1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVk2CQZ4C5zOeyUBP_3zoJh1tTRB9D5Ek',
    appId: '1:1081850466656:ios:191f37a6a8201f94eace05',
    messagingSenderId: '1081850466656',
    projectId: 'chat-app-540b1',
    storageBucket: 'chat-app-540b1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Qh3NdEYk5nl8j1o2HB_X0rpt0MFMW3E',
    appId: '1:1081850466656:web:b80d19a096788d82eace05',
    messagingSenderId: '1081850466656',
    projectId: 'chat-app-540b1',
    authDomain: 'chat-app-540b1.firebaseapp.com',
    storageBucket: 'chat-app-540b1.appspot.com',
    measurementId: 'G-WN1FEBWFMY',
  );
}
